#pragma once
///////////////////////////////////////////////////////////////////////////////
// IEASYSTEM_EVENT_MESSAGE_DISPATCHER_VERSION
//
#ifndef IEASYSTEM_EVENT_MESSAGE_DISPATCHER_VERSION
	#define IEASYSTEM_EVENT_MESSAGE_DISPATCHER_VERSION   "1.00.04"
	#define IEASYSTEM_EVENT_MESSAGE_DISPATCHER_VERSION_N  10004
#endif
